added step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,4 +8,10 @@ jobs:
     steps:
       - name: Say hello
         run: echo "Hello, World!"
-  
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: failed step
+        run: echo "Failed step" && exit 1
+      - name: Say goodbye
+        run: echo "Goodbye, World!"
